# Generated by Django 5.2.4 on 2025-07-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories_bird_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories'),
        ),
    ]
