# Generated by Django 5.2.4 on 2025-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
