# Generated by Django 5.2.4 on 2025-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bird_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
