# Generated by Django 5.2.4 on 2025-08-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bird_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='in_the_red_book',
            field=models.BooleanField(default=False),
        ),
    ]
