# Generated by Django 5.2.4 on 2025-09-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bird_in_the_red_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, default=None, null='True', upload_to='photos/', verbose_name='Фото'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='bird',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='in_the_red_book',
            field=models.BooleanField(default=False, verbose_name='Входит в красную книгу'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг категории'),
        ),
    ]
